### ISSUE TITLE
Preview for past date shows today's running timer

### ISSUE THREAD

**Issue by Archimedyz** [Daniel-Aragao/TogglToJira#1]
# Issue
I ran the the preview command to see what the time logs were for 2 days ago (2023-03-15). The output shows the expected table, but then a second table appears with the currently running timer.

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1493104/225912115-229bed5c-7510-41f2-888e-36bf8175df8a.png">

The time log for that second table is from _today_ (2023-03-17), and so it shouldn't be appearing.

# Details

I'm running windows, and using the tool via git-bash.
I'm using commit `eb6522c064f5fc0866f6a051b15b11eaf1f3ca36`.
In the image above I am using the command `tog`, which is an alias for `node ~/repos/TogglToJira/index.js -fm`

---

If you need additional info, let me know and I'll provide it.

**Comment by Daniel-Aragao** [comment]
Thanks for the comment, it seems you are passing only one date as an argument, as stated in the README.md session, that's essentially using the date as a start period behaviour like a `since` this date.

The command to get the values as you intended would be something similar `tog 2023-03-15:2023-03-17`, considering the second-day exclusive

**Comment by Daniel-Aragao** [comment]
To avoid further confusion the behaviour of the feature was changed to return only the logs from the informed date. If the `since` feature is intended the argument `from=` may be used
